Refactor : 게시글/댓글 API 수정
prgrms-web-devcourse/Team_WAS_YAS_BE pull request #120
Opened 2021-12-17 14:22 UTC by bnminji

## 🚅 PR 한 줄 요약

게시글/댓글 API 수정

## 🧑‍💻 PR 세부 내용

- 게시글/댓글 수정,삭제에 대해 userId 검증 추가 (userValid)
- 게시글 등록 시 이미 등록된 루틴인지 검증 추가 (routineValid)
- Routine 엔티티에 @where 제거 + findByIdAndIsDeletedFalse 추가 
   => 루틴 삭제시에도 게시글엔 루틴 남아있음

2021-12-17 17:22 UTC, LSH0809 requested changes
조금만 변경하면 일단 머지 해도 될것 같아요 대대적인 리팩토링은 추후로 일단 미루죠!!

2021-12-17 17:22 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
> +			final @ApiIgnore @AuthenticationPrincipal JwtAuthentication token, final @PathVariable("id") Long commentId,
제가 생각을 하다가 문득 떠오른게 final을 쓰면 이 변수는 값이 더 안바뀐다라는 의미잖아요? 상수로 사용한다? 근데 이 부분은 변할 여지가 없는 부분이고 이 값을 반환하는 용도가 아닌데 final 키워드를 사용해야 하는건가요?? 민지님이 사용하신 이유가 궁금합니당!! 🤔

2021-12-17 17:22 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
> +		if (!userId.equals(compareUserId)) {
boolean값을 반환하므로 isUserValid로 is라는 단어를 붙여주면 좀 더 메소드 네이밍이 잘 이해가 되지 않을까 생각하는데 어떻게 생각하시나요?!

2021-12-17 17:22 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java
> -                               .collect(Collectors.toList());
저희가 오늘 피드백을 받았는데
```java
c-> !c.isDeleted()
```
로만 해도 충분하다고 해서 이 부분 다음에 적용할 때 있으면 적용하면 좋을 것 같아요

2021-12-17 17:22 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/post/service/PostService.java
> +	}
내부에서만 쓰는 메소드이면 private으로 변경하는 것이 좋을 것 같습니다! 다른 곳에서 호출 할게 아니면 말이죠!

2021-12-17 19:45 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/post/service/PostService.java
> +	}
저도 몇개 public으로 쓴게 있는거 같은데 다음에 리팩토링 할때 변경 해야겠군요~!!

2021-12-18 07:12 UTC, Chaeonida approved these changes
수고하셨습니당~!!

2021-12-18 08:19 UTC, bnminji commented on src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java
> -                               .collect(Collectors.toList());
앗 코드는 아래 부분으로 바꼈는데 그냥 참고용으로 말씀해주신거죠? 감사합니다!

2021-12-18 12:53 UTC, LSH0809 reviewed
머지 후, 제가 리팩토링 및 리뷰 반영하도록 하겠습니다

2021-12-18 12:53 UTC, merged