Feat. 루틴 생성,삭제, 수정 추가 (유저아이디관한 부분 수정 필요)
prgrms-web-devcourse/Team_WAS_YAS_BE pull request #15
Opened 2021-12-07 06:34 UTC by Chaeonida

## 🚅 PR 한 줄 요약

루틴 생성,삭제,수정 기능 추가 

## 🧑‍💻 PR 세부 내용

- 루틴 생성기능 추가 
- 루틴 삭제기능 추가 ( soft delete이용) 
- 루틴 수정기능 추가 ( week 수정)

2021-12-08 09:20 UTC, LSH0809 requested changes
채원님 고생하셨습니다 ㅎㅎ 아직 완성 전의 코드들이니까 다음에 또 수정하셔서 올려주시면 바로 리뷰 하도록 할게요!! 
두 명이서 하느라 많이 힘드실텐데 끝까지 열심히 해요!!! 👍

2021-12-08 09:20 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
> +public class RoutineController {
로그 찍는 부분이 없어서 @Slf4j 어노테이션을 삭제해도 될 것 같은데 어떠신가요?!?

2021-12-08 09:20 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
> +  @Enumerated(EnumType.STRING)
저도 이 부분 공부해서 작성하도록 할게요 👍

2021-12-08 09:20 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
> +@DynamicInsert
soft-delete에 다양한 어노테이션을 활용하셨네요!! 멋집니당 ㅎㅎ

2021-12-08 09:20 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
> +public interface RoutineRepository extends JpaRepository<Routine, Long> {
@Repository 어노테이션은 작성하지 않으셔도 괜찮습니당!!

2021-12-08 09:20 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
> +  }
이번에 새로 코드 스타일 수정했으니까 한번 적용하고 다시 올려주세요!! 수정했는데 불편하면 다시 같이 수정 또 해보죠!

2021-12-08 09:20 UTC, LSH0809 commented on src/test/java/org/prgrms/yas/domain/routine/controller/RoutineControllerTest.java
> +class RoutineControllerTest {
벌써 테스트 코드까지!! 대단하십니다 채원님 ㅎㅎ
테스트 코드를 보니, @BeforeEach를 이용해 데이터를 작성하셔서 활용하셨는데 @Transactional 어노테이션을 추가하면, 마지막에 롤백이 됩니다!! 사용하면 좋을 것 같아요!!

2021-12-09 14:37 UTC, LSH0809 requested changes
전체적으로 주석 제거와 채원님 의견 관련해서 댓글 추가했습니당! 좀만 더 힘내유!!! 👍

2021-12-09 14:37 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
> +    return ResponseEntity.ok(routineDeleteResponse);
변수 선언 말고 아래처럼 바로 return 하는 것은 어떠신가요?! 채원님의 의견이 궁금합니다!!ㅎㅎ
```java
return ResponseEntity.ok(routineService.deleteRoutine(id); 
```

2021-12-09 14:37 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
> +  List<RoutineCategory> routineCategory;
```java
List<RoutineCategory> routineCategory = new ArrayList<>();
```
이렇게 선언과 동시에 초기화를 하는 것이 좋을 것 같아요!! 이유는, 안정성으로 알고 있는데 이 부분에 대해 좀 더 설명을 찾아보고 댓글 추가해드릴게요!!

2021-12-09 14:37 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
> +  //  private Week week;
이 부분도 주석 제거가 필요해 보입니다!!

2021-12-09 14:37 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
> +    return result;
for문에서 Week의 변수를 x로 네이밍하신 이유가 있을까요?? 좀 더 직관적으로 네이밍을 하는 것은 어떨지 채원님의 의견이 궁금합니당 ㅎㅎㅎ

2021-12-09 14:37 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCategory.java
>  public enum RoutineCategory {
여기에 @RequiredArgsConstructor가 필요한 이유가 궁금합니다!!!

2021-12-09 14:37 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/Week.java
> +  //  }
이 부분도 주석 제거 해주시면 좋을 것 같습니당ㅎㅎㅎ

2021-12-09 14:37 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java
> +  private List<String> weeks;
이 부분이 오늘 함께 이야기 했던 부분인 것 같아요!! 저도 이 부분 좀 더 공부해보고 추후에 공유해드릴게요!! ㅎㅎ

2021-12-09 14:37 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateRequest.java
> +
이 부분에 공백 제거 부탁드릴게요!!!

2021-12-09 14:37 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
> +                                 routineCreateRequest.getRoutineCategory()))
채원님 이 부분 보니까, routineCreateRequest.getWeeks() 부분에 마지막 괄호가 가독성이 부족한 것 같은데 이런 식으로 스타일 같이 변경해보는건 어떻게 생각하시나요?!
```java
.weeks(
                                 routineCreateRequest.getEnumWeeks(
                                               routineCreateRequest.getWeeks()
                                  )
)
```

2021-12-09 14:37 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
> +                                                                               routine.getWeeks()))
이 부분도 위와 비슷한 생각입니다 마지막에 괄호를 내리는 것이 좋을 것 같은데 채원님의 생각이 궁금해요!! ㅎㅎㅎ

2021-12-09 14:37 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
> +// 여기서 유저 매핑 해주세요
이 부분도 주석 제거 부탁드릴게요!!ㅎㅎ

2021-12-09 14:37 UTC, LSH0809 commented on src/test/java/org/prgrms/yas/domain/routine/service/RoutineServiceTest.java
> +    //Assertions.assertThat(findRoutine.getWeeks()).isEqualTo();
주석 제거 부탁드릴게요!!!ㅎㅎ

2021-12-09 14:52 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
> +                                 routineCreateRequest.getRoutineCategory()))
네 변경하는것도 좋을거 같아욥!!

2021-12-09 14:53 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
> +    return result;
for문 쓸때 변수명을 x 를 쓰는 습관이 있어서 습관적으로 저렇게 썼는데 week로 변경하였습니당

2021-12-09 14:56 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
> +    return ResponseEntity.ok(routineDeleteResponse);
이거 같은 경우는 코드 길이가 짧은데 RoutineCreateResposne 같은 경우는 routineService.saveRoutine(token.getId(),
        routineCreateRequest); 와 같이 길어서 따로 변수를 뺐는데 혹시 불편하실까유?! 변수 빼는 것도 하나로 통일 하는게 좋을거 같다는 생각이 있었는데 어떻게 생각하시나요?!

2021-12-09 15:13 UTC, LSH0809 requested changes
조금만 더 수정하면 1차적으로 구현완료는 될 것 같습니당!! 고생하셨어요!!

2021-12-09 15:13 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
> +  List<RoutineCompletion> routineCompletions = new ArrayList<>();
이 부분 private이 어디로 .. 갔죠?! 생략하게 되면 접근제어자가 default가 되어 접근 권한의 범위가 패키지까지 커지게 됩니당 그래서 private은 넣어주면 좋을 것 같아유!

2021-12-09 15:13 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java
> +public class RoutineCreateRequest {
현재 기본생성자가 public으로 되어있는데 안전성 측면에서 protected로 설정하는 것이 좋을 것 같습니다~ 이 부분에 대한 내용은 아마 기본생성자 protected vs public 으로 검색하면 찾으실 수 있을 거에유

2021-12-09 15:13 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateResponse.java
> +    }
이 부분에도 변수명이 x로 설정되어 있네요~ 수정 부탁드릴게요~

2021-12-09 15:13 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
> +    return ResponseEntity.ok(routineDeleteResponse);
아니요 아니요 불편하다기보다 채원님이 변수선언을 한 이유가 궁금했습니당 ㅎㅎ음.. 통일?! 한번 같이 이야기해보죠!

2021-12-09 15:13 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java
> +    }
여기도 변수 네이밍이 x로 되어 있습니당 ㅎㅎ 수정 부탁드릴게요!!

2021-12-09 15:13 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateRequest.java
> +    return result;
여기도 변수 네이밍이 x로 설정되어있습니당!!!

2021-12-09 15:13 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
> +  }
enum으로 요일정보와 카테고리를 구현했으니 String -> enum형태로 작성하는게 낫지 않을까 싶은데 일단 이 부분은 좀 더 고민해보죠!!

2021-12-09 15:28 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
> +  List<RoutineCompletion> routineCompletions = new ArrayList<>();
위에 week도 private설정 안되어있어서 뺐는데 둘다 private으로 했습니당!!

2021-12-09 15:35 UTC, LSH0809 requested changes
변수명만 수정하시면 될 것 같습니당!!ㅎㅎ

2021-12-09 15:35 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateResponse.java
> +  }
변수 x 발견했어유!

2021-12-09 15:39 UTC, LSH0809 approved these changes
고생하셨습니당!! 다음에 또 리팩토링 해봐유!!!

2021-12-09 15:39 UTC, merged