#16/루틴 전체조회
prgrms-web-devcourse/Team_WAS_YAS_BE pull request #17
Opened 2021-12-07 08:13 UTC by Chaeonida

## 🚅 PR 한 줄 요약

루틴 전체 조회 기능 추가 

## 🧑‍💻 PR 세부 내용
- userId를 통해 전체 조회 
- controller 부분 userId 받아오는 부분 , 테스트 수정 해야함

2021-12-08 09:23 UTC, LSH0809 requested changes
이전 것이 merge가 안된 상태로 PR이 올려져서 이전에 올려주신 거랑 겹치는 부분이 많네요!! 이전 피드백 보시고 함께 수정하면 될 것 같습니당!! 고생하셨어요 ㅎㅎ

2021-12-08 09:23 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
> +public class RoutineController {
이 부분은 제 User 관련해서 보시고 수정하시면 될 것 같아요!!

2021-12-08 09:23 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
> +@DynamicInsert
다양한 어노테이션 활용 좋습니당👍

2021-12-09 07:51 UTC, LSH0809 requested changes
채원님 너무 고생하시고 있어요!! 좀만 더힘내요 ㅎㅎㅎ

2021-12-09 07:51 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
> +//    return ResponseEntity.ok(routineCreateResponse);
수정 끝나셨으면 주석 삭제 해도 될 것 같아요!! ㅎㅎㅎㅎ 👍

2021-12-09 16:17 UTC, LSH0809 requested changes
조금만 수정하면 될 것 같습니당 ㅎㅎㅎ 고생하셨어요 채원님!!

2021-12-09 16:17 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
> +  }
이 부분 코드 스타일이 직관적이지 않은 것 같네요!! .을 기준으로 내리는게 좋을 것 같은데 어떻게 생각하시나요?! 이 부분 같이 이야기 해서 스타일만 수정하면 될 것 같습니당

2021-12-09 16:17 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
> +  }
앞서 말했던, 변수명 x 수정 부탁드릴게요~~!

2021-12-09 16:17 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
> +  }
stream 활용 멋집니다!!!ㅎㅎㅎ 👍

2021-12-09 16:17 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
> +  List<Routine> getByUser(User user);
find~가 아닌, get~으로 하면 어떤 특징이 있나요?! 궁금합니당 🤔

2021-12-09 16:17 UTC, LSH0809 commented on src/test/java/org/prgrms/yas/domain/routine/service/RoutineServiceTest.java
> +  }
아래 줄 공백 제거 부탁드릴게요!!

2021-12-09 16:23 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
> +  List<Routine> getByUser(User user);
find로 하면 optional로 감싸져서 나오고 get으로 하면 optional로 안감싸져서 나옵니당!! 아직 예외 처리가 확실치  않아서 저렇게 했었는데 바꾸긴 해야겠네요 ㅎㅎ

2021-12-09 16:23 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
> +  }
오잉 아까 pr에서 수정했는데 여기엔 제대로 안들어가 있네유 ㅠㅠ 수정했습니다!!

2021-12-09 16:37 UTC, LSH0809 requested changes
코드 스타일 세팅 바뀐 부분만 적용해서 style로 커밋 주시면 될 것 같습니당!! 👍

2021-12-09 16:37 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
> +  List<Routine> getByUser(User user);
리스트라서 orElseThrow로 예외처리를 할 필요가 없는 건가요? 그래서 get으로 하신건가요??? (그냥 궁금해서
, 저는 처음봐서 여쭤봅니당 ㅎㅎㅎ 👍 )

2021-12-09 16:42 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
> +  List<Routine> getByUser(User user);
유저가 루틴을 안만든 상태일 수도 있는데 루틴이 없다고 에러가 날 이유가 없는거 같아서 get으로 했습니당!! ㅎㅎ

2021-12-09 16:43 UTC, LSH0809 approved these changes
고생하셨습니다 ㅎㅎㅎ 끝까지 함께 파이팅해보죠!!! 👍

2021-12-09 16:43 UTC, merged