feat : #241/루틴완료 후 후기 작성 기능 추가
prgrms-web-devcourse/Team_WAS_YAS_BE pull request #249
Opened 2022-01-16 13:20 UTC by Chaeonida

## 🚅 PR 한 줄 요약

루틴완료 후 후기 작성 기능 추가

## 🧑‍💻 PR 세부 내용

- 사진 업데이트를 위한 RoutineStatusImage 엔티티 추가 
- RoutineStatus 테이블에 emoji, content 필드 추가
- 이모지, 글, 사진 업데이트를 할 수 있다.

2022-01-16 17:30 UTC, LSH0809 requested changes
파일 업로드에 대한 yml 파일이 지금 10MB로 제한되어 있는데 이 부분은 어떻게 생각하시나요? 다중 업로드 코드를 작성했으니까 이 부분에 대해서도 채원님이랑 프론트 분들 이야기를 들어보면 좋을 것 같습니당!!!

2022-01-16 17:30 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
> +	private Integer emoji;
후기 작성안할 때 null값을 저장할 지, 0 과같이 임의이 상수를 넣을지 이 부분 프론트 분들이랑 이야기를 해보죠!

2022-01-16 17:30 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatusImage.java
> +	) {
여백이 이상하네요.. 음.. 스타일에 대해서 나중에 같이 수정해보죠!

2022-01-16 17:30 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
> +		//RoutineStatusImage에 저장
주석 삭제 해주시면 감사하겠습니다!!

2022-01-16 17:30 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
> +				System.out.println("routineStatusImage.getId() : "+  routineStatusImage.getId());
출력문이 필요하면 logger를, 그렇지 않으면 삭제 해주셔도 될 것 같습니당

2022-01-17 09:43 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatusImage.java
> +	) {
넵 좋아요~!!

2022-01-20 18:04 UTC, LSH0809 requested changes
전체적으로 댓글은 안 추가했지만 주석 삭제만 해주시면 될 것 같습니당! 고생하셨어요!!ㅎㅎ

2022-01-20 18:04 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java
> +	List<RoutineStatus> getByDate(@Param("yearMonth")String yearMonth);
sql문 안에서 substring으로 문자열을 파싱할 수 있군요?! 오호... 이걸 몰랐네요 그러면 java의 기본 문자나 숫자에 대한 메소드들이 다 적용되는 건가요??

2022-01-20 18:04 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
> +				routineStatusImageRepository.delete(routineStatusImage);
이부분 상수로 선언을 해주면 좀 더 깔끔할 것 같습니당! + 매직넘버도 처리 부탁할게요!!

2022-01-21 12:21 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java
> +	List<RoutineStatus> getByDate(@Param("yearMonth")String yearMonth);
저도 이번에 처음알았습니당~!! 네 내장된 메소드인거같아요 :)

2022-01-21 12:50 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java
> +	List<RoutineStatus> getByDate(@Param("yearMonth")String yearMonth);
이부분 원래 조회쪽에서 올렸어야했는데 잘못올라간거같아요 ㅠㅠ

2022-01-22 14:41 UTC, LSH0809 reviewed
넵!! 확인했습니다 고생하셨어유!

2022-01-22 14:42 UTC, LSH0809 approved these changes

2022-01-22 14:49 UTC, merged