feat : #41/미션 전체 조회 기능 추가
prgrms-web-devcourse/Team_WAS_YAS_BE pull request #42
Opened 2021-12-12 10:29 UTC by Chaeonida

## 🚅 PR 한 줄 요약

미션 전체 조회 기능 추가 

## 🧑‍💻 PR 세부 내용

루틴아이디를 통해 아이디에 맞는 루틴들 조회 가능

2021-12-12 11:28 UTC, LSH0809 requested changes
채원님 고생하셨습니다~ 제가 리뷰 단 부분 확인 부탁드릴게요!!

2021-12-12 11:28 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
> +
이 부분 개행 제거 부탁드립니다!

2021-12-12 11:28 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
>  	private Routine routine;
이 부분도 이전 PR 에서 햇떤 리뷰와 마찬가지로 이후, 리팩토링할 때 cascade 옵션이나 orphanRemoval 고려해주시면 될 것 같아요!

2021-12-12 11:28 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailResponse.java
> +	}
compareTo를 이용해서 정렬을 하셨군요! 👍  그럼 Repository에서 ~orderByOrder라는 네임드쿼리를 작성하지 않고 이렇게 작성한 이유가 어떤 것 때문인가요? 저는 네임드쿼리를 사용할 것으로 생각했는데 채원님 코드를 보니 제가 이 부분에 대해서 생각을 못한 것 같습니당ㅎㅎ

2021-12-12 11:28 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
> +	) {
이 부분에 대한 코드는 아니고 RoutineController에 있는 다른 코드에 관해서 궁금한 점이 있는데 그 부분이 이번에 작성된게 아니라 여기에다가 리뷰를 달게요! 
-> 다른 컨트롤러 메소드를 보니 URI에 {id}로 명시했는데 @Pathvariable의 이름에도 "id"이렇게 명시가 되어있는 것을 확인했습니당. 혹시 이러한 부분도 의도적으로 모두 작성하고자 하신건가요?! (궁금해서 여쭤봅니다 ㅎㅎ)

2021-12-12 11:28 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
> +	}
name이나 emoji 같은 경우 this.필드명으로 되어있고, color의 경우에는 getter 메소드를 사용되어있는 것 같은데 이 부분에 대해서 일관되게 작성해주시면 좋을 것 같습니다!!

2021-12-12 11:28 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
>  	}
이 부분도 위의 응답객체로의 반환 메소드와 같이 일관되게 작성을 해주면 좋을 것 같습니다?! 🤔

2021-12-12 11:28 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
>  		List<Routine> routines = routineRepository.getByUser(user);
NotFoundUserException에 대해서 커스텀 입섹션이 아닌, 표준 입섹션을 사용하셨군요 혹시 이 부분에 대해서는 표준예외를 작성한 이유가 있을까요?? 
-> 만약, 커스텀 입섹션을 미처 작성하지 못한 이유이면 제가 만들어 놓은 커스텀 입섹션을 보시는 것도 좋을 것 같아요!

2021-12-12 11:28 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
>  		               .collect(toList());
항상 보면 저는 stream이나 람다나 사용을 잘 못하는 느낌이 드는데 채원님은 stream에 대해 잘 적용하시는 것 같아요ㅎㅎ 멋집니당👍

2021-12-12 11:28 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
> +	}
커스텀 입섹션을 만들어서 사용하셨군요 ㅎㅎㅎ 👍 👍 👍  이 부분에 대해서는 우리 회의때도 한번 이야기를 했지만 이후 리팩토링 하면서 좀 더 좋은 계층구조, 좀 더 이상적인 예외처리 방법을 생각해보죠!!

2021-12-12 12:31 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
>  		List<Routine> routines = routineRepository.getByUser(user);
앗 이부분은 이번 pr에는 제가 변수명만 바꾸고 이전에 저희가 예외처리에 대해 확실히 정하기 전에 작성했던 코드라 후에 리팩토링 이슈 만들어서 수정 예정입니다!!

2021-12-12 12:35 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailResponse.java
> +	}
저희가 실제로 반환하는 객체는 Mission 이아닌 MissionDetailResponse 이기 때문에 여기서 정렬이 일어나는게 더 확실 할 것 같아서 compareTo를 이용하여 작성하였습니다!!

2021-12-12 12:50 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
> +	) {
혹시 수형님은 어떻게 작성하시나요?! 습관적으로 저렇게 작성하긴 했는데 수형니므이 코드스타일도 궁금합니당~!!

2021-12-12 12:51 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
> +	}
좋아요!! 수형님덕에 예외처리에 대해 많은걸 배워갈수 있어서 좋았습니당 ㅎㅎㅎ

2021-12-13 07:00 UTC, LSH0809 approved these changes
채원님 고생하셨습니다 ㅎㅎㅎ 채원님이 아무래도 많은 도메인을 담당하고 계셔서 힘드실건데.. 조금만 더 힘내요!!

2021-12-13 07:00 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailResponse.java
> +	}
그렇다면, repository에서 데이터를 가지고 올 때는 정렬이 안된 상태이고, 이후 DTO로 변환되어서 정렬을 하는 방식이 되는 건가요??!

2021-12-13 07:00 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
> +	) {
저는 id가 여러개 들어오지 않으면 그냥 id로 습관적?으로 작성하는 편입니다 ㅎㅎㅎㅎ 채원님의 코드처럼 작성하면 좀 더 직관적인 장점이 있겠네요!! 👍

2021-12-13 07:08 UTC, bnminji approved these changes
수고하셨습니다!

2021-12-13 07:21 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailResponse.java
> +	}
네 맞습니당 
미션자체를 레포지토리에서 직접적으로 가져오지는 않고 엔티티 통해 가져와서 DTO로 변환후에 정렬하는게 더 맞다고 생각했습니다!! ㅎㅎ

2021-12-13 07:23 UTC, merged