feat : #32/댓글 등록,삭제,수정 기능
prgrms-web-devcourse/Team_WAS_YAS_BE pull request #45
Opened 2021-12-12 14:36 UTC by bnminji

## 🚅 PR 한 줄 요약

댓글 등록,삭제,수정 기능에 대한 Controller(+Test), Service(+Test)

## 🧑‍💻 PR 세부 내용
- 게시글 댓글 등록
- [ ] Controller
- [ ] Service
- [ ] Controller Test
- [ ] Service Test
- 게시글 댓글 삭제
- [ ] Controller
- [ ] Service
- [ ] Controller Test
- [ ] Service Test
- 게시글 댓글 수정
- [ ] Controller
- [ ] Service
- [ ] Controller Test
- [ ] Service Test

2021-12-12 18:13 UTC, Chaeonida approved these changes
민지님 고생하셨습니당!!

2021-12-12 18:13 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/comment/dto/CommentDetailResponse.java
> +    this.content = comment.getContent();
응답 객체 만들때 엔티티 안에서 했었는데 이런 방법도 있었군요!!  더 깔끔한거 같습니당 ㅎㅎ

2021-12-13 04:40 UTC, bnminji commented on src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
> +      final @RequestBody CommentCreateRequest createRequest)
음 저번 팀에서는 받은 값 변경될 일이 없기 때문에 final로 상수화시켜줬었어요!

2021-12-13 07:08 UTC, LSH0809 requested changes
민지님 고생하셨습니다! 조금만 더 다같이 힘내죠!!ㅎㅎ

2021-12-13 07:08 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
> +  @PostMapping("/{id}/comments")
Swagger 어노테이션 사용해서 간략하게 설명 작성 부탁드릴게요!!

2021-12-13 07:08 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
>    private RoutinePost routinePost;
foreignKey가 테이블을 생성할 때 관련있는 만큼, 이미 테이블을 생성해놨으니 작성하지 않아도 괜찮지 않을까 싶은데 민지님은 어떠신가요?

2021-12-13 07:08 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/comment/exception/NotFoundCommentException.java
> +}
혹시, 제가 global 패키지에 NotFoundException 생성해놨는데 그 부분이 아직 반영이 안되었나요?! 만약, 있으면 NotFoundException 상속받아서 작성하면 좋을 것 같습니다!!

2021-12-13 07:08 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
> +    RoutinePost routinePost = postRepository.findById(postId)
람다 관련해서 간격이 안되어 있는 것 같습니다! 
```java
.orElseThrow( () ->new NotFoundUserException(ErrorCode.NOT_FOUND_RESOURCE_ERROR));
```
이렇게 정렬 한번 부탁드릴게요

2021-12-13 07:08 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
> +      throws NotFoundUserException, NotFoundRoutineException {
혹시 예외를 여기서 또 던지는 이유가 있을 까요? 삭제하면 정상적으로 실행이 안되나요??! 
(아래 메소드들에도 다 작성이 되어 있어서 궁금합니다!)

2021-12-13 07:08 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
> +}
전체적으로 final 키워드를 많이 사용하시는 군요! 👍

2021-12-13 07:14 UTC, bnminji commented on src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
>    private RoutinePost routinePost;
넵 반영했습니다!

2021-12-13 07:33 UTC, bnminji commented on src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
> +      throws NotFoundUserException, NotFoundRoutineException {
예전에 JPA 실습했을 때 강사님이 사용했던 스타일을 쓴 것인데, 저도 이 부분에 대해 다시 알아보겠습니다!

2021-12-13 08:42 UTC, LSH0809 requested changes
궁금한 부분에 대해 리뷰 달았으니 다시 한번 확인 부탁드릴게요!!

2021-12-13 08:42 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
> +  @Operation(summary = "댓글 등록 컨트롤러")
스웨거로 설명 추가해주셨으니까 주석은 삭제 부탁드릴게요!

2021-12-13 08:42 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
> +      final @RequestBody CommentCreateRequest commentCreateRequest
자동정렬했는데 final @PathVariable ~ 이 부분 안내려가나요?

2021-12-13 08:42 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
> +  }
@PatchMapping을 사용하신 이유가 있을까요? @DeleteMapping으로 사용안하신 이유가 궁금합니다. @DeleteMapping도 @PostMapping의 큰 범주 안에 속하는 것으로 알고 있어서요!

2021-12-13 08:42 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
> +    return ResponseEntity.ok(ApiResponse.of(commentService.updateComment(
throws를 컨트롤러에서 해야하는 이유가 있을까요?? 혹시 이 부분 삭제하면 정상 작동을 안하나요?!

2021-12-13 08:45 UTC, bnminji commented on src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
> +      final @RequestBody CommentCreateRequest commentCreateRequest
넵 안내려가네요..ㅠㅠ

2021-12-14 12:49 UTC, Chaeonida approved these changes
민지님 수고하셨습니당~!! 이제 얼마 안남았는데 같이 힘내요!!

2021-12-14 12:49 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
> -
user에 대한 정보는 필요 없는건가욥?!

2021-12-14 12:49 UTC, Chaeonida commented on src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
> +public class RoutineDto {
다음에 작성하실때는 request와 response구별해서 작성해 주시면 좀 더 명확할거 같습니당~!!

2021-12-14 12:52 UTC, bnminji commented on src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
> +public class RoutineDto {
아 이게 request, response dto가 아니라 reponse안에 있는 객체를 담기위한 DTO이어서 오히려 response를 붙이면 더 가독성이 떨어지는 것 같더라구요ㅠㅠ 그래서 간단하게 ~Dto로 했습니다!

2021-12-14 13:10 UTC, LSH0809 requested changes
민지님 고생하셨습니다ㅎㅎ 조금만 더 힘내죠!

2021-12-14 13:10 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java
> +  private String updatedAt;
이 두개의 타입이 String인 이유가 궁금합니다.

2021-12-14 13:10 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java
> +public class CommentDto {
Dto의 네이밍은 채원님이랑 이야기하신 부분인가요??! 왜냐하면 현재 Dto의 네이밍 컨벤션이 Request or Response인데 Dto라는 네이밍을 작성하셔서 궁금했습니당

2021-12-14 13:10 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
> +		this.missions = routine.getMissions().stream().map(MissionDto::new).collect(Collectors.toList());
이 부분 자동 정렬이 적용이 안되었나요?! .을 기준으로 내려가는 것으로 알고 있어서요

2021-12-14 13:10 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/post/exception/NotFoundRoutinePostException.java
> +}
줄 정렬 부탁드릴게요~

2021-12-14 13:10 UTC, LSH0809 commented on src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java
> +  }
서비스에서 생성되는 부분을 확인했는데 이와 같은 경우는 @Builder 어노테이션을 제거해도 되지 않을까요? 빌더를 적용하는 부분이 혹시 이외에 또 있을까요?!

2021-12-14 13:14 UTC, bnminji commented on src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java
> +  private String updatedAt;
DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss") 로 LocalDateTime을 포맷해줄 경우 String으로 반환되기 때문에 string지정해줬습니다.

2021-12-14 13:16 UTC, bnminji commented on src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
> +		this.missions = routine.getMissions().stream().map(MissionDto::new).collect(Collectors.toList());
넵 정렬해서 다시 올리겠습니다!

2021-12-14 13:18 UTC, bnminji commented on src/main/java/org/prgrms/yas/domain/post/dto/CategoryDto.java
> +}
PostDetailResponse안의 객체에 대한 dto입니다!

2021-12-14 13:24 UTC, bnminji commented on src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
> +		                                   .orElseThrow(() -> new NotFoundCommentException(ErrorCode.NOT_FOUND_RESOURCE_ERROR));
음 네 우선 기본적인 기능에 대해서 api작성하고 이후에 리팩토링할 예정입니다!

2021-12-15 09:26 UTC, closed without merging